server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    add_header X-Server-Name $hostname always;

    location / {
        try_files $uri $uri/ /index.html;
        expires 10m;
    }

    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
